# Generated by Django 5.0.4 on 2024-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=250)),
                ('Task_status', models.BooleanField(default=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
